### ISSUE TITLE
Issues with the template

### ISSUE THREAD

**Issue by angelolloqui** [itstheceo/kotlin-mobile-multiplatform-template#1]
Hi!

First, thanks for sharing this template, it seems to match exactly what I was looking for: Kotlin multiplatform (iOS/Android) + SwiftUI + cocoapods + ktor + coroutines! Excelent!

However, I have tried downloading the project and importing it in my Android Studio (AS 4.0 Beta 3) and make it run. I have found several issues:

1. Android/SampleJvm.kt: `actual` keyword can not find expectation in the IDE giving error `Actual object 'Platform' has no corresponding expected declaration`. However, when compiling and android the android app module, it seems to run properly and changing the `name()` value to something else reflects properly in the UI so it is being compiled.
2. iOS/SampleTestNative.kt: `kotlin.test` imports can not be found. I do not see how to make tests run
3. Xcode project: After doing `pod install` I got compilation errors because it could not find the `core` pod. I managed to solve it by playing with the `cocoapods` and `xcodeSync` gradle tasks, together with extra `pod install`. After solving the compilation issue, the iOS app was not launching due to core framework not found on runtime. It can be solved by adding the `pod 'core', :path => '../core'` on the top level as well.
4. When trying to add dependencies on the kotlin code for iOS/Android, the IDE does not seem to find any of them, which makes it unworkable. I could not find a way to add Ktor o UIKit related calls into the iOS kotlin files (nor Android)

Do you have any clue of what could be happening? it seems to me that the IDE is not capable of finding out the dependencies added in the core gradle file, and the rest is just the result of that. Somehow, I guess that gradle can find them, or otherwise the Android app and iOS core Framework would not compile.

_UPDATE_: If I try to import it on Android Studio 3.6.2 I get a similar result.

_UPDATE 2:_ I have seen in the logs some errors pointing out that the linked libraries (ktor and the rest) are not compatible with Kotlin 1.3.71. May this be the reason? What version of Kotlin should I have for this? (although that would not explain issue 1. I guess)

Thanks!

**Comment by itstheceo** [comment]
Hello

I would recommend using IntelliJ IDEA instead of Android Studio, hopefully this will help resolve many of the issues you are seeing (#2 and #3) as it is the preferred IDE for kotlin multiplatform development. It should feel very familiar to Android Studio if you haven't used it before.

I will look into #1 and #4 this as it appears to be happening for me now too, and they are probably related issues.

It has been a while, and I have been reluctant to update the template to the bleeding edge of Kotlin development because all dependencies must be built with the same ABI version in order to work together on iOS without error. Having said that, the template was created using Kotlin 1.3.61. I will see if I can get some time to update it. 

If you are looking for a more well maintained template, I would recommend looking at [KaMP Kit](https://github.com/touchlab/KaMPKit)! The guys over at Touchlab have done a great job with it, and are very active in the community.

It shouldn't be too difficult to get SwiftUI running on their template.

**Comment by angelolloqui** [comment]
Thanks for your answer! I will give a try to KaMP as you suggested!

**Comment by itstheceo** [comment]
Closing this for now. Updated the readme to redirect users to KaMP Kit.
